[workspace]
members = ["quoridor_gui", "quoridor_core", "quoridor_server_tcp", "quoridor_web/server", "quoridor_web/client"]

[profile.dev.package."*"]
opt-level = 3

[profile.release.client]
lto = true
opt-level = 'z'
codegen-units = 1